# Generated by Django 4.2.5 on 2023-09-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inventory', models.CharField(default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['price'], name='CourseraAPI_price_1d151f_idx')],
            },
        ),
    ]
