# Generated by Django 4.2.5 on 2023-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseraAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(),
        ),
    ]
